revision 542
Fri Sep  7 17:08:37 CEST 2001 - mantel@suse.de

- moved Linux-ABI stuff to i386 specific file
- added personalities needed by Linux-ABI

-------------------------------------------------------------------
Fri Sep  7 15:58:03 CEST 2001 - werner@suse.de

- network script: Add workaround ethernet driver modules:
  Try to load them in order even if a device is disabled.

-------------------------------------------------------------------
Fri Sep  7 15:23:40 CEST 2001 - stepan@suse.de

- new mk_initrd: added option -s to add boot splash animation, if
  installed and concatenate the bootsplash jpeg file to initrd.
- new aaa_base_splash.diff: cleaned up diff and test for rc.config
  variable $BOOT_SPLASH before playing any animation.

-------------------------------------------------------------------

diff --git a/aaa_base_splash.diff b/aaa_base_splash.diff
--- a/aaa_base_splash.diff
+++ b/aaa_base_splash.diff
@@ -1,6 +1,65 @@
---- etc/init.d/rc	Tue Aug 21 17:09:39 2001
-+++ etc/init.d/rc	Thu Aug 23 15:18:57 2001
-@@ -111,6 +111,9 @@
+diff -urN etc/init.d/boot etc/init.d/boot
+--- etc/init.d/boot	Sat Sep  1 19:26:00 2001
++++ etc/init.d/boot	Fri Sep  7 14:39:05 2001
+@@ -122,6 +122,8 @@
+     fi
+ fi
+ 
++rc_splash "early stop"
++
+ #
+ # s390 is 'like' serial console(better: no console ttys at all)
+ # and we don't have access to the HW Clock
+@@ -140,6 +142,8 @@
+    FSCK_PROGRESSBAR=""
+ fi
+ 
++rc_splash "fsck start"
++
+ #
+ # Find and activate volume groups (HM 1/1/1999)
+ #
+@@ -351,6 +355,7 @@
+ echo "Activating remaining swap-devices in /etc/fstab..."
+ swapon -a &> /dev/null
+ rc_status -v1 -r
++rc_splash "fsck stop"
+ 
+ # set and adjust the CMOS clock
+ if test "$HWCLOCK_ACCESS" != "no" ; then
+@@ -420,6 +425,8 @@
+     rc_status -v -r
+ fi
+ 
++rc_splash "bootnetwork start"
++
+ #
+ # initialize loopback device
+ #
+@@ -674,6 +681,7 @@
+ # Let YaST2 finish its installation, if you installed with YaST2
+ #
+ if test -f /var/lib/YaST2/runme_at_boot ; then
++    rc_splash "YaST"
+     exec 0<> $REDIRECT 1>&0 2>&0
+     # if yast2 failed, this ensures proper system setup
+     touch /var/lib/YaST2/run_suseconfig
+diff -urN etc/init.d/halt etc/init.d/halt
+--- etc/init.d/halt	Sat Sep  1 13:13:00 2001
++++ etc/init.d/halt	Fri Sep  7 14:39:05 2001
+@@ -16,6 +16,8 @@
+ trap "echo" SIGINT SIGSEGV SIGQUIT SIGTERM
+ set +e
+ 
++rc_splash "reboot"
++
+ case "$0" in
+ 	*halt)
+ 		message="The system will be halted immediately."
+diff -urN etc/init.d/rc etc/init.d/rc
+--- etc/init.d/rc	Mon Aug 27 17:08:00 2001
++++ etc/init.d/rc	Fri Sep  7 14:39:05 2001
+@@ -115,6 +115,9 @@
      test $# -gt 1 && echo -e "$attn$runrc/: more than one link for service $service$norm"
      test -x "$1"  && continue
  
@@ -10,56 +69,30 @@
      # Log to /var/log/boot.msg
      blogger "$i stop"
  
-@@ -139,6 +142,9 @@
-     set -- $prerc/K$rex$service
+@@ -144,6 +147,9 @@
      test $# -gt 1 && echo -e "$attn$prerc/: more than one link for service $service$norm"
      test -x "$1"  && continue
-+
+ 
 +    # send information to splash icon viewer.
 +    rc_splash  "$i start"
- 
++
      # Log to /var/log/boot.msg
      blogger "$i start"
---- etc/init.d/boot	Tue Aug 21 17:09:45 2001
-+++ etc/init.d/boot	Fri Aug 24 11:42:33 2001
-@@ -108,6 +108,8 @@
-     fi
- fi
  
-+rc_splash "early stop"
+@@ -175,6 +181,9 @@
+ #    FAIL : 7 - program is not running (doing "start")
+ #    OK   : 7 - program is not running (doing "stop")
+ #
 +
- #
- # s390 is 'like' serial console(better: no console ttys at all)
- # and we don't have access to the HW Clock
-@@ -126,6 +128,8 @@
-    FSCK_PROGRESSBAR=""
- fi
- 
-+rc_splash "fsck start"
++rc_splash "master"
 +
- #
- # Find and activate volume groups (HM 1/1/1999)
- #
-@@ -337,6 +341,7 @@
- echo "Activating remaining swap-devices in /etc/fstab..."
- swapon -a &> /dev/null
- rc_status -v1 -r
-+rc_splash "fsck stop"
- 
- # set and adjust the CMOS clock
- if test "$HWCLOCK_ACCESS" != "no" ; then
-@@ -414,6 +419,8 @@
-     /usr/sbin/zic -l $TIMEZONE
-     rc_status -v -r
- fi
-+
-+rc_splash "bootnetwork start"
- 
- #
- # initialize loopback device
---- etc/rc.status	Thu Aug 23 14:03:02 2001
-+++ etc/rc.status	Fri Aug 24 12:40:39 2001
-@@ -26,6 +26,10 @@
+ echo -n "Master Resource Control: "
+ echo -e "runlevel ${RUNLEVEL} has been ${stat}${extd}reached${norm}"
+ if test -n "$failed" ; then
+diff -urN etc/rc.status etc/rc.status
+--- etc/rc.status	Tue Aug  7 16:55:00 2001
++++ etc/rc.status	Fri Sep  7 14:45:59 2001
+@@ -31,6 +31,10 @@
  #    \015          carriage return (without newline)
  #
  
@@ -70,56 +103,12 @@
  if test -z "$LINES" -o -z "$COLUMNS" ; then
      eval `stty size 2>/dev/null | (read L C; \
  	  echo LINES=${L:-24} COLUMNS=${C:-80})`
-@@ -189,4 +193,8 @@
+@@ -196,4 +200,8 @@
  function rc_exit ()
  {
      exit $_rc_status_all
 +}
 +function rc_splash()
 +{
-+    test "$_rc_splash" -eq 1 && /bin/splash "$1"
++    test "$BOOT_SPLASH" != "no" && test "$_rc_splash" -eq 1 && /bin/splash "$1"
  }
---- etc/init.d/rc	Wed Aug 29 17:32:00 2001
-+++ etc/init.d/rc	Thu Aug 30 18:34:20 2001
-@@ -181,6 +181,9 @@
- #    FAIL : 7 - program is not running (doing "start")
- #    OK   : 7 - program is not running (doing "stop")
- #
-+
-+rc_splash "master ${RUNLEVEL}"
-+
- echo -n "Master Resource Control: "
- echo -e "runlevel ${RUNLEVEL} has been ${stat}${extd}reached${norm}"
- if test -n "$failed" ; then
---- etc/init.d/halt	Mon Aug 20 16:28:00 2001
-+++ etc/init.d/halt	Thu Aug 30 18:40:26 2001
-@@ -16,6 +16,8 @@
- trap "echo" SIGINT SIGSEGV SIGQUIT SIGTERM
- set +e
- 
-+rc_splash "reboot"
-+
- case "$0" in
- 	*halt)
- 		message="The system will be halted immediately."
---- etc/init.d/boot	Fri Sep  7 03:14:25 2001
-+++ etc/init.d/boot	Fri Sep  7 03:15:28 2001
-@@ -681,6 +681,7 @@
- # Let YaST2 finish its installation, if you installed with YaST2
- #
- if test -f /var/lib/YaST2/runme_at_boot ; then
-+    rc_splash "YaST"
-     exec 0<> $REDIRECT 1>&0 2>&0
-     # if yast2 failed, this ensures proper system setup
-     touch /var/lib/YaST2/run_suseconfig
---- etc/init.d/rc	Fri Sep  7 03:13:10 2001
-+++ etc/init.d/rc	Fri Sep  7 03:14:04 2001
-@@ -182,7 +182,7 @@
- #    OK   : 7 - program is not running (doing "stop")
- #
- 
--rc_splash "master ${RUNLEVEL}"
-+rc_splash "master"
- 
- echo -n "Master Resource Control: "
- echo -e "runlevel ${RUNLEVEL} has been ${stat}${extd}reached${norm}"
