- automatically adjust initrd size

diff --git a/sbin/mk_initrd b/sbin/mk_initrd
--- a/sbin/mk_initrd
+++ b/sbin/mk_initrd
@@ -11,7 +11,7 @@
 #   exit code > 0
 #
 
-# Version 1.12
+# Version 1.13
 #
 # Author: Steffen Winterfeldt <wfeldt@suse.de>
 # (c) 1999 SuSE GmbH
@@ -19,6 +19,9 @@
 # (c) 2000 Karsten Keil   option and kernel 2.4 support
 #
 # ChangeLog:
+#
+# 5/3/2001:	v1.13 Stefan Rauch <srauch@suse.de>
+#  - automatically adjust initrd size
 #
 # 13/1/2001:	v1.12
 #  - continue with next kernel/initrd on errors
@@ -159,9 +162,9 @@ fi
 static_shell=/bin/ash.static
 static_insmod=/sbin/insmod.static
 
-# initrd size
-image_blocks=5000
-image_inodes=100
+# maximum initrd size
+image_blocks=10000
+image_inodes=2000
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # should be nothing to change below...
@@ -170,12 +173,17 @@ tmp_mnt=/tmp/mnt$$
 tmp_msg=/tmp/msg$$
 lx_rc=$tmp_mnt/linuxrc
 is_mounted=
+is_mounted_small=
 
 clean_up () {
   [ "$is_mounted" ] && umount $tmp_mnt
   is_mounted=
+  [ "$is_mounted_small" ] && umount $tmp_mnt_small
+  is_mounted_small=
   rm -f $tmp_initrd $tmp_initrd.gz $tmp_msg
+  rm -f $tmp_initrd_small $tmp_initrd_small.gz
   [ -d $tmp_mnt ] && rmdir $tmp_mnt
+  [ -d $tmp_mnt_small ] && rmdir $tmp_mnt_small
 }
 
 error () {
@@ -211,8 +219,6 @@ then
     echo root device is LVM
     static_shell=/bin/ash
     static_insmod=/sbin/insmod
-    image_blocks=6000
-    image_inodes=2000
 fi
 
 if [ "$root_dir" != / ] ; then
@@ -260,7 +266,6 @@ for k in $kernels ; do
     }
 
     mkdir $tmp_mnt
-
     dd if=/dev/zero of=$tmp_initrd bs=1k count=$image_blocks 2>/dev/null
     mke2fs -q -F -b 1024 -m 0 -N $image_inodes $tmp_initrd 2>/dev/null
     tune2fs -i 0 $tmp_initrd >/dev/null 2>&1
@@ -336,12 +341,34 @@ for k in $kernels ; do
 	echo "umount /proc" >> $lx_rc
     fi
 
+    # now create a second initrd with minimal size
+    
+    img_size=`expr \`df -k $tmp_mnt | sed '1d' | awk '{print $3}'\` + 1000`
+    tmp_mnt_small=${tmp_mnt}_small
+    mkdir $tmp_mnt_small
+    tmp_initrd_small=${tmp_initrd}_small
+    
+    dd if=/dev/zero of=$tmp_initrd_small bs=1k count=$img_size 2>/dev/null
+    mke2fs -q -F -b 1024 -m 0 -N $image_inodes $tmp_initrd_small 2>/dev/null
+    tune2fs -i 0 $tmp_initrd_small >/dev/null 2>&1
+    
+    mount -oloop $tmp_initrd_small $tmp_mnt_small || { 
+      error 3 "failed to mount image"
+    }
+    is_mounted_small=1
+    
+    rmdir $tmp_mnt_small/lost+found
+    cp -a $tmp_mnt/* $tmp_mnt_small || error 6 "copy big image to small image failed"
+    
+    umount $tmp_mnt_small
+    is_mounted_small=
+    
     umount $tmp_mnt
     is_mounted=
 
-    gzip -9 $tmp_initrd
+    gzip -9 $tmp_initrd_small
 
-    cp -f $tmp_initrd.gz $ii || {
+    cp -f $tmp_initrd_small.gz $ii || {
       oops 8 "failed to install initrd"
       continue
     }
