- new versions of:   - etc/csh.cshrc   - sbin/rctab   - man page for rctab   - etc/skel/.emacs (for emacs 20) - lib/YaST/bootsetup.conf:  deleted perl stuff (is done by SuSEconfig.perl now) - added kde suids to /etc/permission.{easy,secure} - added etc/nsswitch.conf - sbin/init.d/boot:  initialize pnp a little bit earlier.   Variable START_ISAPNP added. - added /opt/gnome/lib to etc/ld.so.conf.in - etc/profile added /opt/gnome/bin to path. - SuSEconfig:  added KDEDIR, GNOMEDIR, XADIDIR, QTDIR, DV_IMMED_HELP,   MAPLE, RASMOLPATH, DMARSCONF and CRPATH for /etc/SuSEconfig/*   most of them were in /etc/profile

diff --git a/sbin/rctab b/sbin/rctab
--- a/sbin/rctab
+++ b/sbin/rctab
@@ -31,8 +31,24 @@ fi
 #
 : ${todo=""}
 : ${optkey=""}
-: ${tmp=/tmp/rctmp$$}
 : ${EDITOR=vi}
+#
+tmpdir=/tmp/rctmpdir.$$
+tmp="${tmpdir}/rctmp"
+
+trap "rm -rf $tmpdir" 0 1 3 4 7 9 13 15
+trap "exit 1" 2
+mkdir -p ${tmpdir}
+if test $? -gt 0 -o ! -d ${tmpdir} ; then
+    echo "Error $0: cannot create $tmpdir" 1>&2
+    exit 1
+fi
+chmod 0700 $tmpdir
+#
+# make sort secure
+#
+export TMPDIR=$tmpdir
+
 #
 # Some defaults: format of our sorting number in start and stop links
 #
@@ -683,10 +699,6 @@ case "$todo" in
 	genlevels
 	inittable
 	placein
-	trap "rm -f $tmp" 0 1 3 4 7 9 13 15
-	trap "exit 1" 2
-	touch $tmp
-	test -e $tmp || { echo "Error $0: cannot open $tmp" 1>&2 ; exit 1; }
 	line=$(echo "$head"|wc -l)
 	line=$((line + 1))
 	echo "$head" >> $tmp
