- added umountizo to halt script (if binary is existing and   intermezzo filesystems are mounted) - updated comments in skeleton

diff --git a/files/etc/init.d/skeleton b/files/etc/init.d/skeleton
--- a/files/etc/init.d/skeleton
+++ b/files/etc/init.d/skeleton
@@ -1,15 +1,17 @@
 #! /bin/sh
-# Copyright (c) 1995-2000 SuSE GmbH Nuernberg, Germany.
+# Copyright (c) 1995-2002 SuSE GmbH Nuernberg, Germany.
 #
 # Author: Kurt Garloff <feedback@suse.de>
 #
-# init.d/FOO
+# /etc/init.d/FOO
 #
 #   and symbolic its link
 #
-# /sbin/rcFOO
+# /(usr/)sbin/rcFOO
 #
-# System startup script for some example service or daemon
+# LSB compliant service control script; see http://www.linuxbase.org/spec/
+# 
+# System startup script for some example service or daemon FOO (template)
 #
 ### BEGIN INIT INFO
 # Provides: FOO
@@ -17,14 +19,25 @@
 # Required-Stop:  $remote_fs $syslog
 # Default-Start:  3 5
 # Default-Stop:   0 1 2 6
-# Description:    Start FOO to allow XY and provide YZ.
+# Description:    Start FOO to allow XY and provide YZ
+#	continued on second line by '#<TAB>'
 ### END INIT INFO
+# 
+# Note on Required-Start: It does specify the init script ordering,
+# not real dependencies. Depencies have to be handled by admin
+# resp. the configuration tools (s)he uses.
 
-# Source SuSE config
-. /etc/rc.config
+# Source SuSE config (if still necessary, most info has been moved)
+test -r /etc/rc.config && . /etc/rc.config
 
+# Check for missing binaries (stale symlinks should not happen)
 FOO_BIN=/usr/sbin/FOO
 test -x $FOO_BIN || exit 5
+
+# Check for existence of needed config file and read it
+FOO_CONFIG=/etc/sysconfig/FOO
+test -r $FOO_CONFIG || exit 6
+. $FOO_CONFIG
 
 # Shell functions sourced from /etc/rc.status:
 #      rc_check         check and set local and overall rc status
@@ -35,6 +48,7 @@ test -x $FOO_BIN || exit 5
 #      rc_failed <num>  set local and overall rc status to <num><num>
 #      rc_reset         clear local rc status (overall remains)
 #      rc_exit          exit appropriate to overall rc status
+#      rc_active	checks whether a service is activated by symlinks
 . /etc/rc.status
 
 # First reset status of this service
@@ -61,7 +75,7 @@ case "$1" in
 	## Start daemon with startproc(8). If this fails
 	## the echo return value is set appropriate.
 
-	# NOTE: startproc return 0, even if service is 
+	# NOTE: startproc returns 0, even if service is 
 	# already running to match LSB spec.
 	startproc $FOO_BIN
 
@@ -126,11 +140,11 @@ case "$1" in
 	#rc_status -v
 	;;
     status)
-	echo -n "Checking for FOO: "
+	echo -n "Checking for service FOO: "
 	## Check status with checkproc(8), if process is running
 	## checkproc will return with exit status 0.
 
-	# Status has a slightly different for the status command:
+	# Return value is slightly different for the status command:
 	# 0 - service running
 	# 1 - service dead, but /var/run/  pid  file exists
 	# 2 - service dead, but /var/lock/ lock file exists
@@ -142,7 +156,7 @@ case "$1" in
 	;;
     probe)
 	## Optional: Probe for the necessity of a reload,
-	## give out the argument which is required for a reload.
+	## print out the argument which is required for a reload.
 
 	test /etc/FOO/FOO.conf -nt /var/run/FOO.pid && echo reload
 	;;
